### ISSUE TITLE
math.tcl is lost

### ISSUE THREAD

**Issue by HaoxinGuo** [ArashSaeidpour/BridgePM#1]
hello, I want to use your script to build bridge model,there some error hapened.
can you fix it ? thank you
![](https://raw.githubusercontent.com/HaoxinGuo/PicBed/master/Blog/error1.png)

**Comment by ArashSaeidpour** [comment]
Hi ! Thanks for letting me know about this bug, I just added the math.tcl file to the repo. Feel free to reach out again if you had any other troubles with the code.

**Comment by HaoxinGuo** [comment]
Hi! Thanks for your reply,But there occurs some other issues.
It needs more datas in Run.txt. You can see the code in ```Input.tcl```.
Thank you!
![](https://raw.githubusercontent.com/HaoxinGuo/PicBed/master/Blog/errpr2.png)
![](https://raw.githubusercontent.com/HaoxinGuo/PicBed/master/Blog/info3.png)

**Comment by ArashSaeidpour** [comment]
Sorry for your trouble, let me see if I can reproduce the same error and get back to you with the answer.

**Comment by ArashSaeidpour** [comment]
The entire codebase has been revised and tested.
